# Table clearing environment trainer hyper parameters configs

reward:
  time: -5 # per second
  action_penalty: -1
  travel_to_target: 100 # per meter
  travel_to_dest: 100 # per meter

  grasped: 5.0
  delivered: 10.0
  enter_src_tray_not_grasped: 1.0

  dropped: -10.0
  collided: -10.0
  exit_src_tray_not_grasped: -2.0

  max_time: -10.0
  max_actions: -10.0

episode:
  max_time: 300 #seconds
  max_actions: 5000
