# Table clearing environment trainer hyper parameters configs

reward:
  time: -5 # per second
  action_penalty: -1
  travel_to_target: 100 # per meter
  travel_to_dest: 100 # per meter

  grasped: 500.0
  delivered: 1000.0
  enter_src_tray_not_grasped: 50.0

  dropped: -1000.0
  collided: -1000.0
  exit_src_tray_not_grasped: -100.0

  max_time: -1000.0
  max_actions: -1000.0

episode:
  max_time: 300 #seconds
  max_actions: 5000
