# Table clearing environment trainer hyper parameters configs

reward:
  time: 0 # per second
  action_penalty: -1
  travel_to_target: 0 # per meter
  travel_to_dest: 0 # per meter

  grasped: 100.0
  delivered: 200.0
  enter_src_tray_not_grasped: 10.0

  dropped: -200.0
  collided: -1000.0
  exit_src_tray_not_grasped: -22.0

  max_time: -3.0
  max_actions: -3.0

episode:
  max_time: 180 #seconds
  max_actions: 3000
